### ISSUE TITLE
Another bug when working with a special preset

### ISSUE THREAD

**Issue by AnClark** [rncbc/synthv1#17]
I'm continue testing SynthV1 with REAPER. Today I've found another bug.

## Preset with issue

<details>
<summary>Preset file</summary>

```xml
<!DOCTYPE synthv1>
<preset name="Sci-fi Flying 3" version="0.9.22.32git.e83414.dirty [develop]">
 <params>
  <param index="0" name="DCO1_SHAPE1">3</param>
  <param index="1" name="DCO1_WIDTH1">0.99904084205627441</param>
  <param index="2" name="DCO1_BANDL1">0</param>
  <param index="3" name="DCO1_SYNC1">-0</param>
  <param index="4" name="DCO1_SHAPE2">2</param>
  <param index="5" name="DCO1_WIDTH2">1</param>
  <param index="6" name="DCO1_BANDL2">0</param>
  <param index="7" name="DCO1_SYNC2">-0</param>
  <param index="8" name="DCO1_BALANCE">0.00459640845656395</param>
  <param index="9" name="DCO1_DETUNE">0.12084111571311951</param>
  <param index="10" name="DCO1_PHASE">0.24624323844909668</param>
  <param index="11" name="DCO1_RINGMOD">0.69593149423599243</param>
  <param index="12" name="DCO1_OCTAVE">0</param>
  <param index="13" name="DCO1_TUNING">0</param>
  <param index="14" name="DCO1_GLIDE">0.53395593166351318</param>
  <param index="15" name="DCO1_ENVTIME">0.5</param>
  <param index="16" name="DCF1_ENABLED">1</param>
  <param index="17" name="DCF1_CUTOFF">0.049604400992393494</param>
  <param index="18" name="DCF1_RESO">0</param>
  <param index="19" name="DCF1_TYPE">-0</param>
  <param index="20" name="DCF1_SLOPE">2</param>
  <param index="21" name="DCF1_ENVELOPE">0.52650606632232666</param>
  <param index="22" name="DCF1_ATTACK">0.12538035213947296</param>
  <param index="23" name="DCF1_DECAY">0.5547826886177063</param>
  <param index="24" name="DCF1_SUSTAIN">0.69639170169830322</param>
  <param index="25" name="DCF1_RELEASE">0.56676125526428223</param>
  <param index="26" name="LFO1_ENABLED">1</param>
  <param index="27" name="LFO1_SHAPE">-0</param>
  <param index="28" name="LFO1_WIDTH">1</param>
  <param index="29" name="LFO1_BPM">96.970710754394531</param>
  <param index="30" name="LFO1_RATE">0.60932046175003052</param>
  <param index="31" name="LFO1_SYNC">0</param>
  <param index="32" name="LFO1_SWEEP">0.16489776968955994</param>
  <param index="33" name="LFO1_PITCH">-0.44400355219841003</param>
  <param index="34" name="LFO1_BALANCE">-0.83026361465454102</param>
  <param index="35" name="LFO1_RINGMOD">0.065328940749168396</param>
  <param index="36" name="LFO1_CUTOFF">-0.082021772861480713</param>
  <param index="37" name="LFO1_RESO">-1</param>
  <param index="38" name="LFO1_PANNING">-0.36444777250289917</param>
  <param index="39" name="LFO1_VOLUME">-0.016584195196628571</param>
  <param index="40" name="LFO1_ATTACK">0.023350061848759651</param>
  <param index="41" name="LFO1_DECAY">0.75658077001571655</param>
  <param index="42" name="LFO1_SUSTAIN">0.98371082544326782</param>
  <param index="43" name="LFO1_RELEASE">0.33027938008308411</param>
  <param index="44" name="DCA1_VOLUME">1</param>
  <param index="45" name="DCA1_ATTACK">0.47323614358901978</param>
  <param index="46" name="DCA1_DECAY">0.17921185493469238</param>
  <param index="47" name="DCA1_SUSTAIN">1</param>
  <param index="48" name="DCA1_RELEASE">0.48525571823120117</param>
  <param index="49" name="OUT1_WIDTH">0</param>
  <param index="50" name="OUT1_PANNING">0</param>
  <param index="51" name="OUT1_FXSEND">1</param>
  <param index="52" name="OUT1_VOLUME">0.37999999523162842</param>
  <param index="53" name="DEF1_PITCHBEND">0.20000000298023224</param>
  <param index="54" name="DEF1_MODWHEEL">0.20000000298023224</param>
  <param index="55" name="DEF1_PRESSURE">0.20000000298023224</param>
  <param index="56" name="DEF1_VELOCITY">0.20000000298023224</param>
  <param index="57" name="DEF1_CHANNEL">0</param>
  <param index="58" name="DEF1_MONO">0</param>
  <param index="59" name="DCO2_SHAPE1">1</param>
  <param index="60" name="DCO2_WIDTH1">0.95175236463546753</param>
  <param index="61" name="DCO2_BANDL1">0</param>
  <param index="62" name="DCO2_SYNC1">0</param>
  <param index="63" name="DCO2_SHAPE2">2</param>
  <param index="64" name="DCO2_WIDTH2">0.85896515846252441</param>
  <param index="65" name="DCO2_BANDL2">-0</param>
  <param index="66" name="DCO2_SYNC2">-0</param>
  <param index="67" name="DCO2_BALANCE">0.16226750612258911</param>
  <param index="68" name="DCO2_DETUNE">0.00879296101629734</param>
  <param index="69" name="DCO2_PHASE">0.60693609714508057</param>
  <param index="70" name="DCO2_RINGMOD">0</param>
  <param index="71" name="DCO2_OCTAVE">-2</param>
  <param index="72" name="DCO2_TUNING">0</param>
  <param index="73" name="DCO2_GLIDE">0.6011883020401001</param>
  <param index="74" name="DCO2_ENVTIME">0.5</param>
  <param index="75" name="DCF2_ENABLED">1</param>
  <param index="76" name="DCF2_CUTOFF">0.17431449890136719</param>
  <param index="77" name="DCF2_RESO">0.061738401651382446</param>
  <param index="78" name="DCF2_TYPE">0</param>
  <param index="79" name="DCF2_SLOPE">1</param>
  <param index="80" name="DCF2_ENVELOPE">1</param>
  <param index="81" name="DCF2_ATTACK">0.071791119873523712</param>
  <param index="82" name="DCF2_DECAY">0.45163959264755249</param>
  <param index="83" name="DCF2_SUSTAIN">0.54555881023406982</param>
  <param index="84" name="DCF2_RELEASE">0.59177297353744507</param>
  <param index="85" name="LFO2_ENABLED">1</param>
  <param index="86" name="LFO2_SHAPE">3</param>
  <param index="87" name="LFO2_WIDTH">0.52772045135498047</param>
  <param index="88" name="LFO2_BPM">293.73703002929687</param>
  <param index="89" name="LFO2_RATE">0.26580163836479187</param>
  <param index="90" name="LFO2_SYNC">-0</param>
  <param index="91" name="LFO2_SWEEP">-0.6928020715713501</param>
  <param index="92" name="LFO2_PITCH">0.40426778793334961</param>
  <param index="93" name="LFO2_BALANCE">0.086928427219390869</param>
  <param index="94" name="LFO2_RINGMOD">0.40468224883079529</param>
  <param index="95" name="LFO2_CUTOFF">-0.21630749106407166</param>
  <param index="96" name="LFO2_RESO">0.61858391761779785</param>
  <param index="97" name="LFO2_PANNING">-0.62312740087509155</param>
  <param index="98" name="LFO2_VOLUME">0.045989662408828735</param>
  <param index="99" name="LFO2_ATTACK">0.002971498528495431</param>
  <param index="100" name="LFO2_DECAY">0.29200303554534912</param>
  <param index="101" name="LFO2_SUSTAIN">1</param>
  <param index="102" name="LFO2_RELEASE">0.37740409374237061</param>
  <param index="103" name="DCA2_VOLUME">0.22757060825824738</param>
  <param index="104" name="DCA2_ATTACK">0</param>
  <param index="105" name="DCA2_DECAY">0.043900132179260254</param>
  <param index="106" name="DCA2_SUSTAIN">0.68884670734405518</param>
  <param index="107" name="DCA2_RELEASE">0.13113300502300262</param>
  <param index="108" name="OUT2_WIDTH">0</param>
  <param index="109" name="OUT2_PANNING">0</param>
  <param index="110" name="OUT2_FXSEND">1</param>
  <param index="111" name="OUT2_VOLUME">0.40000000596046448</param>
  <param index="112" name="DEF2_PITCHBEND">0.20000000298023224</param>
  <param index="113" name="DEF2_MODWHEEL">0.20000000298023224</param>
  <param index="114" name="DEF2_PRESSURE">0.20000000298023224</param>
  <param index="115" name="DEF2_VELOCITY">0.20000000298023224</param>
  <param index="116" name="DEF2_CHANNEL">0</param>
  <param index="117" name="DEF2_MONO">0</param>
  <param index="118" name="CHO1_WET">0</param>
  <param index="119" name="CHO1_DELAY">0.5</param>
  <param index="120" name="CHO1_FEEDB">0.5</param>
  <param index="121" name="CHO1_RATE">0.5</param>
  <param index="122" name="CHO1_MOD">0.5</param>
  <param index="123" name="FLA1_WET">0</param>
  <param index="124" name="FLA1_DELAY">0.5</param>
  <param index="125" name="FLA1_FEEDB">0.5</param>
  <param index="126" name="FLA1_DAFT">0</param>
  <param index="127" name="PHA1_WET">0</param>
  <param index="128" name="PHA1_RATE">0.5</param>
  <param index="129" name="PHA1_FEEDB">0.5</param>
  <param index="130" name="PHA1_DEPTH">0.5</param>
  <param index="131" name="PHA1_DAFT">0</param>
  <param index="132" name="DEL1_WET">0</param>
  <param index="133" name="DEL1_DELAY">0.5</param>
  <param index="134" name="DEL1_FEEDB">0.5</param>
  <param index="135" name="DEL1_BPM">180</param>
  <param index="136" name="REV1_WET">0.5</param>
  <param index="137" name="REV1_ROOM">0.5</param>
  <param index="138" name="REV1_DAMP">0.5</param>
  <param index="139" name="REV1_FEEDB">0.5</param>
  <param index="140" name="REV1_WIDTH">0</param>
  <param index="141" name="DYN1_COMPRESS">0</param>
  <param index="142" name="DYN1_LIMITER">1</param>
  <param index="143" name="KEY1_LOW">0</param>
  <param index="144" name="KEY1_HIGH">127</param>
 </params>
</preset>
```
</details>

## How to reveal this bug

1. Load this preset;
2. Play note Db7 -> E3 -> Db7.

## GDB Backtrace

```
Thread 9 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 16832.0xe00]
--Type <RET> for more, q to quit, c to continue without paging--
synthv1_wave::interp (this=0x3268fd0, i=4294967277, itab=8, alpha=-4.2949673e+09) at ../src/synthv1_wave.h:144
144                     const float x0 = frames[i];
(gdb) bt
#0  synthv1_wave::interp (this=0x3268fd0, i=4294967277, itab=8, alpha=-4.2949673e+09) at ../src/synthv1_wave.h:144
#1  0x00007ffaa061f207 in synthv1_wave::sample (this=0x3268fd0, phase=..., freq=-235.58374)
    at ../src/synthv1_wave.h:135
#2  0x00007ffaa01bd220 in synthv1_oscillator::sample (this=0x1225b6b8, freq=-235.58374) at ../src/synthv1_wave.h:295
#3  0x00007ffa9fef6685 in synthv1_impl::process (this=0x3268fd0, ins=0xb43ea60, outs=0xb43ea50, nframes=2048)
    at ../src/synthv1.cpp:2509
#4  0x00007ffaa04a0bda in synthv1::process (this=0x3267f50, ins=0xb43ea60, outs=0xb43ea50, nframes=2048)
    at ../src/synthv1.cpp:2878
#5  0x00007ffa9fe467b7 in synthv1_lv2::run (this=0x3267f50, nframes=2048) at ../src/synthv1_lv2.cpp:362
#6  0x00007ffa9fd199ed in synthv1_lv2_run (instance=0x3267f50, nframes=2048) at ../src/synthv1_lv2.cpp:828
#7  0x000000014005afde in ?? ()
#8  0x00000001403a2943 in ?? ()
#9  0x00000001403cca72 in ?? ()
#10 0x000000014076a101 in ?? ()
#11 0x000000014077211f in ?? ()
#12 0x0000000140761a9d in ?? ()
#13 0x00000001408c5d28 in ?? ()
#14 0x00000001408e5397 in ?? ()
#15 0x00000001408e546f in ?? ()
#16 0x00007ffb0aed7034 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#17 0x00007ffb0c0c2651 in ntdll!RtlUserThreadStart () from C:\WINDOWS\SYSTEM32\ntdll.dll
#18 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by rncbc** [comment]
maybe fixed by cb59435, in develop branch

thanks

**Comment by AnClark** [comment]
My pleasure!

**Comment by AnClark** [comment]
Bug still exists. Simply swipe the keyboard from high keys (>=C8) to lower keys, then SynthV1 will crash again.

Here's my debugger screenshot. (The Chinese word above "Segmentation Fault" means "Exception occured".)

![image](https://user-images.githubusercontent.com/12870704/124427051-748e0300-dd9d-11eb-832e-085c83d7fcd4.png)

**Comment by rncbc** [comment]
maybe mitigated again with 37cbccd on develop branch

many thanks again for your precious reports
cheers

**Comment by AnClark** [comment]
Both bug resolved, great!

---
What's more, sometimes both SynthV1 and PadthV1 may go mute after switching about 8~10 presets (by host's preset manager, not Vee-One's). 

At that time, MIDI lamp still blinks, but with no sound. Only if I reload an instance it can play sound again.
